# Generated by Django 4.0.5 on 2022-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='cargo_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='opening_bid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
