# Generated by Django 4.0.5 on 2022-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PT', 'Pessoa Transportadora'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
    ]
