# Generated by Django 4.0.5 on 2022-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newuser_delete_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
