# Generated by Django 4.0.5 on 2022-07-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rating_rating_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
