# Generated by Django 4.0.5 on 2022-07-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_surname',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
