# Generated by Django 4.0.5 on 2022-07-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rating_rating_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('Simples', 'Simples'), ('Perecível', 'Perecível'), ('Alto Valor', 'Alto Valor'), ('Frágil', 'Frágil'), ('Perigosa', 'Perigosa')], default='Em Progresso', max_length=15),
        ),
    ]
