# Generated by Django 4.0.5 on 2022-07-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_newuser_email_remove_newuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_test',
        ),
    ]
