# Generated by Django 4.0.5 on 2022-07-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shipping_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Em Progresso', 'Em Progresso'), ('Finalizado', 'Finalizado')], default='Ativo', max_length=15),
        ),
    ]
