# Generated by Django 4.0.5 on 2022-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shipping_user_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='distance',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='at_auction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
