# Generated by Django 4.0.5 on 2022-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_shipping_distance_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='delivery_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='departure_location',
            field=models.CharField(max_length=100),
        ),
    ]
